all:
	iverilog -o cpu.out MUX32.v PC.v Adder.v CPU.v Instruction_Memory.v Pipe_IF_ID.v Hazard_Detection_Unit.v Control.v Immgen.v Register_Equal.v MUXcontrol.v Registers.v Pipe_ID_EX.v MUX32_3.v ALU.v ALU_Control.v Forwarding_Unit.v Pipe_EX_MEM.v DataMemory.v Pipe_MEM_WB.v testbench.v

